language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
  - yarn global add greenkeeper-lockfile@1
  - yarn global add commentator
before_script:
  - greenkeeper-lockfile-update
  - npm prune
  - npm run benchmark | commentator
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_script:
- greenkeeper-lockfile-upload