language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'stable'
before_install:
  - yarn global add greenkeeper-lockfile@1
script:
  - yarn
  - yarn tsc
before_script:
  - greenkeeper-lockfile-update
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
after_script:
  - greenkeeper-lockfile-upload